
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fabricio.pvilla
 */
public class Adicionar extends javax.swing.JFrame {

    /**
     * Creates new form adicionar
     */
    public Adicionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeReceita = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceita = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Receita");
        getContentPane().setLayout(null);

        txtNomeReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeReceita);
        txtNomeReceita.setBounds(120, 40, 270, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome da receita:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 100, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 80, 40);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(120, 400, 270, 40);

        txtReceita.setColumns(20);
        txtReceita.setRows(5);
        jScrollPane1.setViewportView(txtReceita);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 110, 270, 280);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lovely-hand-drawn-coffee-seamless-pattern-cute-doodle-background-great-for-banners-wallpapers-wrapping-fabrics-vector-design-2JDJ309.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-110, -190, 980, 690);

        setSize(new java.awt.Dimension(501, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeReceitaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String i,n;
        i = txtNomeReceita.getText();
        n = txtReceita.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root",""); 
            
            PreparedStatement st = conectar.prepareStatement("INSERT INTO receitas VALUES(?,?)");
            st.setString(1,i);
            st.setString(2,n);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "cadastro realizado com sucesso");
            txtNomeReceita.setText("");
            txtReceita.setText("");
            txtNomeReceita.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showInternalMessageDialog(null, "entre em contato com o suporte e informe o erro:"+ ex.getMessage());
        } catch (SQLException ex) {
            String erro = ex.getMessage();
            if(erro.contains("Duplycate entry")){
                JOptionPane.showMessageDialog(null, "Receitaa adicionada");
            }else{
            JOptionPane.showInternalMessageDialog(null, "entre em contato com o suporte e informe o erro:"+ ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNomeReceita;
    private javax.swing.JTextArea txtReceita;
    // End of variables declaration//GEN-END:variables
}
