
import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Casa
 */
public class Ajuda extends javax.swing.JFrame {

    /**
     * Creates new form atendimento
     */
    public Ajuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbProblema = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuda");
        getContentPane().setLayout(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(170, 40, 240, 50);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 50, 90, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(170, 110, 240, 50);

        jLabel2.setText("Email:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 120, 90, 30);

        cmbProblema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reclamações ", "Dúvidas", "Sugestões ", "Comentários" }));
        cmbProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProblemaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbProblema);
        cmbProblema.setBounds(170, 180, 240, 60);

        jLabel3.setText("Qual o seu problema:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 150, 40);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 260, 240, 180);

        jLabel4.setText("Descrição do seu problema:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 250, 160, 80);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(200, 450, 180, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1352183.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-1220, -10, 1790, 670);

        setSize(new java.awt.Dimension(530, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String n,e,c,d;
        n = txtNome.getText();
        e = txtEmail.getText();
        c = (String) cmbProblema.getSelectedItem().toString();
        d = txtDescricao.getText();
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root",""); 
            
            PreparedStatement st = conectar.prepareStatement("INSERT INTO ajuda VALUES(?,?,?,?)");
            st.setString(1,n);
            st.setString(2,e);
            st.setString(3,c);
            st.setString(4,d);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "enviado com sucesso");
            txtNome.setText("");
            txtEmail.setText("");
            txtDescricao.setText("");
            
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showInternalMessageDialog(null, "entre em contato com o suporte e informe o erro:"+ ex.getMessage());
        } catch (SQLException ex) {
            String erro = ex.getMessage();
            if(erro.contains("Duplycate entry")){
                JOptionPane.showMessageDialog(null, "enviado");
            }else{
            JOptionPane.showInternalMessageDialog(null, "entre em contato com o suporte e informe o erro:"+ ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void cmbProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProblemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cmbProblema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
