/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fabricio.pvilla
 */
public class Empresas extends javax.swing.JFrame {

    /**
     * Creates new form Empresas
     */
    public Empresas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listEmpresas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresas de Café");
        setBackground(new java.awt.Color(102, 51, 0));
        getContentPane().setLayout(null);

        listEmpresas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        listEmpresas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        listEmpresas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Estado:         Nome:", "CE                 GRUPO TRES CORACOES", "SP                 JACOBS DOUWE EGBERTS BR COM. DE CAFES LTDA", "SP                 MELITTA DO BRASIL IND. E COM. LTDA.", "SE                 INDS. ALIMENTS. MARATA LTDA.", "PB                 SAO BRAZ S/A IND. E COM. DE ALIMENTOS S.A", "MG                COOP. REGIONAL DE CAFEICULTORES EM GUAXUPE LTDA. – COOXUPE", "SP                 CAFE PACAEMBU LTDA.", "GO                CAFE RANCHEIRO AGRO INDL. LTDA.", "MG                FOODS IND. E COM. LTDA", "MG                CAFE BOM DIA LTDA.", " ", "Essas são algumas empresas que fabricam café no Brasil", " ", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEmpresas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 60, 590, 300);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3coracoes_aquisicao.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-50, 0, 790, 450);

        setSize(new java.awt.Dimension(754, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listEmpresas;
    // End of variables declaration//GEN-END:variables
}
