/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fabricio.pvilla
 */
public class Qualidade extends javax.swing.JFrame {

    /**
     * Creates new form Qualidade
     */
    public Qualidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstQualidade = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Qualidade de um café");
        getContentPane().setLayout(null);

        lstQualidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 3, true));
        lstQualidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lstQualidade.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Para saber se o café é de qualidade tem três meios de analisar:", " ", "-> Primeiro: pelo seu aroma, existe vários tipos de grãos de café pelo mundo ", "e quando estão sendo moídos ou sendo feitos cada um tem um aroma diferente;", "-> Segundo: pelo paladar, os cafés normalmente são amargos, só que uns tem esse", "amargor mais forte e outros ele é mais suave, e vai de cada pessoa escolher o seu ", "gosto preferido;", "-> E terceiro e o mais importante: pela forma de fazer a torra ou saber como ele foi ", "feito. A torra do café é um processo crucial no desenvolvimento do sabor, aroma ", "e cor dos grãos de café. Durante a torra, os grãos são expostos a altas temperaturas, ", "geralmente entre 180°C e 240°C, por um período que varia de acordo com o tipo de café e ", "o resultado desejado. A torra pode ser clara, média ou escura, cada uma produzindo ", "características de sabor e aroma distintas." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstQualidade);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 40, 650, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20536292.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-1040, -160, 1940, 780);

        setSize(new java.awt.Dimension(813, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qualidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qualidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qualidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qualidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qualidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstQualidade;
    // End of variables declaration//GEN-END:variables
}
